
name: Make

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Convert README.md to index.html
      run: |
        pip install md-to-html
        md-to-html --input README.md --output index.html
        python3 script.py
    - name: Uploading the converted index.html
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
